### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by javierggt**
This PR mostly just modernizes this package.

This PR does not change the information shown, except that it uses mica acq_stats as its source. If we do not want to use the mica acq_stats files instead of sybase, I can change it back.

It does the following:
- Make it a Ska package, including:
  - automated build.
  - automated linting.
  - modern setup using `pyproject.toml`.
  - changing the directory structure a bit.
- rewrite `make_toc.pl` in python
- modernize `acq_stat_reports.py`, including:
  - use mica acq_stats instead of sybase
  - replace a function for binomial errors by the one in chandra_aca.star_probs (sot/chandra_aca/pull/171)
  - replace uses of `os.path` with `pathlib`.
  - replace uses of `Chandra.Time` with `CxoTime`.
  - black/ruff
- modernize `acq_summarize.py`
  - Remove plotting of a defunct trend line. 
  - use standard `main`/`get_parser` structure
  - replace uses of `os.path` with `pathlib`.
  - replace uses of `Chandra.Time` with `CxoTime`.
  - black/ruff

## Testing

I ran the commands in the task schedule, briefly looked at the plots, and navigated the output tree.

I made symbolic links ponting from `www/ASPECT_ICXC/acq_stat_reports/data` and `www/ASPECT_ICXC/acq_stat_reports/web` to the current data/web directoriesin SKA. Removed the directories I expect to be modified. Ran the commands almost like in the task schedule:
```
acq-stat-reports -v debug \
    --datadir www/ASPECT_ICXC/test_review_outputs/acq_stat_reports/pr-4/data \
    --webdir www/ASPECT_ICXC/test_review_outputs/acq_stat_reports/pr-4/web \
    --url /aspect/test_review_outputs/acq_stat_reports/pr-4/web
acq-stat-reports-toc \
    --webdir www/ASPECT_ICXC/test_review_outputs/acq_stat_reports/pr-4/web
acq-stat-reports-summary \
    --datadir www/ASPECT_ICXC/test_review_outputs/acq_stat_reports/pr-4/data \
    --webdir www/ASPECT_ICXC/test_review_outputs/acq_stat_reports/pr-4/web
```

The output is [here](https://icxc.cfa.harvard.edu/aspect/test_review_outputs/acq_stat_reports/pr-4/web/)

I verified that these and only these intervals were updated: 2024-M07, 2024-M08, 2024-Q3, 2024-Q4, 2024-S2, 2025-S1, 2024.

The data does look different, since we switched to mica acq stats.

### CODE REVIEW

**Comment by jeanconn** [comment]
@javierggt in our tagup you mentioned a plot wasn't updated in your test outputs.  Which plot was that?  And I figure you will re-request reviews when that is fixed.

**Comment by jeanconn** [comment]
Do you have a skare3 package recipe ready-to-go for this too?

**Comment by jeanconn** [comment]
And maybe put the version machinery in the init?

**Comment by jeanconn** [comment]
When I run acq-stat-reports I get 
```
/fido.real/conda/envs/ska3-masters/lib/python3.11/site-packages/acq_stat_reports/acq_stat_reports.py:304: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
```
I think we can leave that as a known issue and have a future version either close the figures or change the warning tolerance.

**Comment by jeanconn** [comment]
It looks like the links to the failed star reports aren't correct, but I think that is user error for the test runs when supplying 'url'? 

They go to links like https://icxc.cfa.harvard.edu/aspect/test_review_outputs/acq_stat_reports/pr-4/web/2024/Q4/www/ASPECT_ICXC/test_review_outputs/acq_stat_reports/pr-4/web/2024/Q4/failed_acq_10.0_stars_list.html

**Comment by javierggt** [comment]
for the links to come out right, you need to specify the url. See the commands I ran in the functional checks. If the URLs are wrong, you might inadvertently go to the actual official pages.

**Comment by jeanconn** [comment]
The links are wrong *in* the official test outputs, so I thought that was your user error when I called it out.

**Comment by jeanconn** [comment]
It might actually be a tiny functional issue in the PR.  I'm looking at https://icxc.cfa.harvard.edu/aspect/test_review_outputs/acq_stat_reports/pr-4/web/2024/M08/index.html and the "failed" link above the plots works but the links in the table at the bottom do not.

**Comment by javierggt** [comment]
@jeanconn I made a few extra commits that fix:
- too many open figures
- missing files in install
- broken links in fail_acqs table

I also removed the use of a file that has not been updated for nine years and causes the crazy trendline in the summary page.

**Comment by jeanconn** [comment]
Thanks @javierggt .  Have you rerun the functional outputs?

**Comment by javierggt** [comment]
Yes, I re-ran them. I actually changed the approach (and edited the descriptions of the tests)

**Review by jeanconn — APPROVED** [review]
This looks good to me for a first pass through to modernize.

**Pull request merged**
